# frozen_string_literal: true

# Object Repository of all elements in the android application
module ObjectRepo
  # TEXTFIELD elements
  USERNAME_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_username'
  PHONE_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_phone'
  FIRSTNAME_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_firstname'
  LASTNAME_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_lastname'
  FB_EMAIL_TXTFIELD ||= "xpath~//android.widget.EditText[@content-desc='Mobile Number or Email']"
  FB_PW_TXTFIELD ||= "xpath~//android.widget.EditText[contains(@password, 'true')]"
  GMAIL_TXTFIELD ||= "xpath~//android.widget.EditText[@index='0'])"
  SEARCH_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/search_src_text'
  MENU_SEARCH_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_search'
  EMAIL_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_email'
  PWD_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_password'
  COMMENT_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/comment_edit'
  SEARCH_EDIT_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/search_edit_text'
  EDIT_BIO_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_bio'
  POST_ENTRYFIELD ||= 'id~com.bleacherreport.android.teamstream:id/entryField'
  SEND_MSG_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/message_edit'
  SEARCH_FOR_FRIENDS_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/search'
  EDIT_CHAT_NAME_TXTFIELD ||= 'id~com.bleacherreport.android.teamstream:id/edit_name'

  # BUTTON elements
  ACTION_DONE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/action_cancel'
  ACTION_SKIP_BTN ||= 'id~com.bleacherreport.android.teamstream:id/action_skip'
  ACTION_NEXT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/action_next'
  POPUP_CLOSE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/close-button'
  ACTION_INVITE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/action_invite'
  STEPPER_CONTINUE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_continue_container'
  CONTINUE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_continue'
  CONVERSATION_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_conversation'
  DONE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_done'
  PICK_TEAMS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/welcomePickTeams'
  SIGN_IN_BTN ||= 'id~com.bleacherreport.android.teamstream:id/welcomeSignIn'
  SIGN_UP_BTN ||= 'id~com.bleacherreport.android.teamstream:id/action_signup'

  SIGN_IN_EMAIL_BTN ||= 'id~com.bleacherreport.android.teamstream:id/email_sign_in_button'
  SIGNIN_PHONE_EMAIL_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_signin_phone_or_email'
  SIGN_IN_FB_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_signin_facebook'
  SIGN_IN_GOOGLE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/googleButton'
  MAYBE_LATER_BTN ||= 'id~com.bleacherreport.android.teamstream:id/maybeLaterButton'
  SHOW_LOCAL_TEAMS_BTN ||= 'text~Show Teams Near Me'
  FB_LOG_IN_BTN ||= "xpath~//android.widget.Button[@content-desc='Log In ']"
  FB_CONTINUE_BTN ||= "xpath~//android.widget.Button[@content-desc='Continue as Alex']"
  HOME_BTN ||= 'id~com.bleacherreport.android.teamstream:id/home'
  FIRE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/fire'
  FIRE_COMMENT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/fire_button'
  ALERT_BTN_FIRE ||= 'id~com.bleacherreport.android.teamstream:id/btn_fire'
  MY_BR_BTN ||= 'id~com.bleacherreport.android.teamstream:id/my_br'
  ALERTS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/alerts'
  SCORES_BTN ||= 'id~com.bleacherreport.android.teamstream:id/scores'
  EMAIL_SIGNUP_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_email'
  PROFILE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_profile'
  SEARCH_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_search'
  DM_INBOX_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_inbox'
  MENU_SETTINGS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_settings'
  MENU_EDIT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/edit_button'
  ADD_TEAMS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/add_button'
  SHARE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/share_via_activity_selector'
  SHARE_DM_BTN ||= 'id~com.bleacherreport.android.teamstream:id/share_dm'
  SHARE_DM_CLOSE ||= 'id~com.bleacherreport.android.teamstream:id/btn_back'
  REACTION_BTN ||= "xpath~//android.widget.ImageView[contains(@content-desc, 'Fire')]"
  COMMENT_REACTIONS_COUNT ||= 'id~com.bleacherreport.android.teamstream:id/comment_reactions'
  USER_REACTION_COUNTS ||= 'id~com.bleacherreport.android.teamstream:id/txt_reactions'
  SIGN_OUT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/sign_out_button'
  SAVE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/save_button'
  SETTINGS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/settings_button'
  FEEDBACK_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_send_feedback'
  SHARE_INVITE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_share_invite_link'
  FOLLOW_BTN ||= 'id~com.bleacherreport.android.teamstream:id/follow_button'
  NAVIGATE_UP_BTN ||= "xpath~//android.widget.ImageButton[contains(@content-desc, 'Navigate up')]"
  BOOKMARK_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_bookmark'
  COMMENT_OPTIONS ||= 'id~com.bleacherreport.android.teamstream:id/options'
  SCORES_LEAGUE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/scoresListSubLeagueTitle'
  SETTINGS_SIGN_IN_BTN ||= "xpath~//android.widget.Button[contains(@text, 'Sign In')]"
  CONNECT_FRIENDS_SKIP_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_connect_friends_skip'
  OK_BTN ||= 'id~android:id/button1'
  FIND_FRIENDS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_find_friends'
  ADD_CHAT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/add_chat'
  NEW_CHAT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_add_chat'
  ADD_MEMBER_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_add_member'
  CHAT_DETAILS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_chat_details'
  FIND_FRIENDS_SEARCH ||= 'id~com.bleacherreport.android.teamstream:id/menu_search_username'
  POST_BTN ||= 'id~com.bleacherreport.android.teamstream:id/postButton'
  POST_CANCEL_BTN ||= 'id~com.bleacherreport.android.teamstream:id/cancelButton'
  MYBR_EDIT_PROFILE ||= 'id~com.bleacherreport.android.teamstream:id/edit_profile_button'
  MYBR_EDIT_PHOTO_SKIP_STEPPER ||= 'com.bleacherreport.android.teamstream:id/btn_skip'
  SEND_MESSAGE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_send'
  SEND_FIRST_MSG_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_chat_start_send'
  CREATE_USRNAME_BTN ||= 'id~com.bleacherreport.android.teamstream:id/create_account_button'
  STANDINGS_GCAST_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menuStandings'
  PLAY_NOW_BTN ||= 'id~com.bleacherreport.android.teamstream:id/betStripPlayButton'
  HOW_TO_PLAY_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_bet_center_rules'
  GIF_BTN ||= 'id~com.bleacherreport.android.teamstream:id/gifButton'
  GIF_CLOSE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/closeGif'
  DM_GIF_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_select_gif'
  IMAGE_CLOSE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/closeImage'
  UP_BTN ||= 'id~com.bleacherreport.android.teamstream:id/upButton'
  MEDIA_BTN ||= 'id~com.bleacherreport.android.teamstream:id/mediaButton'
  PICK_ANSWER_BTN ||= 'id~com.bleacherreport.android.teamstream:id/answerBackground'
  TOOLBAR_UP_BTN ||= 'id~com.bleacherreport.android.teamstream:id/toolbarUp'
  JOIN_TEAM_BTN ||= 'id~com.bleacherreport.android.teamstream:id/joinCommunity'
  BET_PAST_RESULTS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/pastResults'
  PARTNER_BTN ||= 'id~com.bleacherreport.android.teamstream:id/partnerLinkout'
  CLOSE_TAB_BTN ||= 'id~com.android.chrome:id/close_button'
  BET_TRACK_TEAM1 ||= 'com.bleacherreport.android.teamstream:id/team_1_box'
  BET_TRACK_TEAM2 ||= 'com.bleacherreport.android.teamstream:id/team_2_box'

  # TEXT link elements
  FB_EMAIL_SIGNUP_LINK ||= 'id~com.bleacherreport.android.teamstream:id/btn_alternative_sign_up'
  FORGOT_PWD_LINK ||= 'id~com.bleacherreport.android.teamstream:id/btn_forgot_password'
  LICENSES_LINK ||= 'id~com.bleacherreport.android.teamstream:id/licenses'
  PRIVACY_POLICY_LINK ||= 'id~com.bleacherreport.android.teamstream:id/privacy_policy'
  TERMS_OF_USE_LINK ||= 'id~com.bleacherreport.android.teamstream:id/terms_of_use'
  PROFILE_PIC_LINK ||= 'id~com.bleacherreport.android.teamstream:id/btn_profile_image'
  EDIT_USERNAME_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_edit_username'
  EDIT_FULLNAME_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_edit_fullname'
  EDIT_DOB_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_edit_birthday'
  EDIT_PHONE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_edit_phone'
  EDIT_EMAIL_BTN ||= 'id~com.bleacherreport.android.teamstream:id/btn_edit_email'
  SIGN_IN_LINK ||= 'id~com.bleacherreport.android.teamstream.debug:id/btn_sign_in'
  SIGN_IN_BTN_GC ||= 'id~com.bleacherreport.android.teamstream:id/btn_sign_in'
  BET_GAMECAST_LINK ||= 'id~com.bleacherreport.android.teamstream:id/gamecastTitle'
  BETTING_LINK ||= 'id~com.bleacherreport.android.teamstream:id/contextualBetting'

  # IMG Elements
  ICON_IMG ||= 'id~com.bleacherreport.android.teamstream:id/icon'
  SML_PROFILE_LOGO ||= 'id~com.bleacherreport.android.teamstream:id/img'
  PROFILE_IMG ||= 'id~com.android.documentsui:id/thumbnail'
  BOOKMARK_IMG ||= 'id~com.bleacherreport.android.teamstream:id/bookmark_img'
  ASSET_IMGVIEW ||= 'id~com.bleacherreport.android.teamstream:id/asset_imageview'
  PREVIOUS_CARET_BTN ||= 'id~com.bleacherreport.android.teamstream:id/previous'
  NEXT_CARET_BTN ||= 'id~com.bleacherreport.android.teamstream:id/next'
  CALENDAR_VIEW ||= 'id~com.bleacherreport.android.teamstream:id/calendarView'
  SORT_COMMENT_CARET ||= 'id~com.bleacherreport.android.teamstream:id/sort_order_caret'
  POST_PROFILE_PHOTO ||= 'id~com.bleacherreport.android.teamstream:id/profilePhoto'
  MYBR_PROFILE_PHOTO ||= 'id~com.bleacherreport.android.teamstream:id/profile_photo'
  MYBR_ADD_PHOTO ||= 'id~com.bleacherreport.android.teamstream:id/add_photo_button'
  MYBR_ADD_PHOTO_INACTIVE ||= 'id~com.bleacherreport.android.teamstream:id/add_photo_button_inactive'
  MYBR_PICK_TEAMS_STEPPER ||= 'id~com.bleacherreport.android.teamstream:id/img_pick_teams_step'
  MYBR_CREATE_ACCT_STEPPER ||= 'id~com.bleacherreport.android.teamstream:id/img_create_account_step'
  ADD_PROFILE_PIC_STEPPER ||= 'com.bleacherreport.android.teamstream:id/img_add_profile_pic_step'
  ADD_YOUR_BIO_STEPPER ||= 'com.bleacherreport.android.teamstream:id/img_add_profile_bio_step'
  CONNECT_WITH_FRIENDS_STEPPER ||= 'com.bleacherreport.android.teamstream:id/img_connect_friends_step'
  PROFILE_COMMENTS ||= 'id~com.bleacherreport.android.teamstream:id/profile_image'
  TEAMSTREAM_GAMECAST ||= 'id~com.bleacherreport.android.teamstream:id/scoreboardTeam1Icon'
  ALERT_BADGE ||= 'id~com.bleacherreport.android.teamstream:id/notifications_badge'
  BETTING_LOGO ||= 'id~com.bleacherreport.android.teamstream:id/bettingLogo'
  BET_TRACK_INFO ||= 'id~com.bleacherreport.android.teamstream:id/info'

  # TEXT Elements
  TXT_STATUS ||= 'id~com.bleacherreport.android.teamstream:id/txt_status'
  TOOLBAR_TITLE ||= 'id~com.bleacherreport.android.teamstream:id/toolbar_title'
  TXT_TITLE ||= 'id~com.bleacherreport.android.teamstream:id/txt_title'
  TXT_SUMMARY ||= 'id~com.bleacherreport.android.teamstream:id/txt_summary'
  TXT_SHADE ||= 'id~com.bleacherreport.android.teamstream:id/txt_shade'
  TXT_NAME ||= 'id~com.bleacherreport.android.teamstream:id/txt_name'
  LRG_LABEL_TXT ||= 'id~com.bleacherreport.android.teamstream:id/largeLabel'
  DISPLAY_NAME_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_stream_name'
  SNACKBAR_TXT ||= 'id~com.bleacherreport.android.teamstream:id/snackbar_text'
  NAME_LABEL_TXT ||= 'id~com.bleacherreport.android.teamstream:id/name'
  SCORES_PAGE_NAME ||= 'id~com.bleacherreport.android.teamstream:id/score_list_page_name'
  SCORES_GAME_TITLE ||= 'id~com.bleacherreport.android.teamstream:id/score_list_header_title'
  SCORES_TAB_PICKER ||= 'id~com.bleacherreport.android.teamstream:id/league_picker_item_name'
  SCORES_TEAM_NAME ||= 'id~com.bleacherreport.android.teamstream:id/scoreListTeam1NameAndRecord'
  SCORES_STAT ||= 'id~com.bleacherreport.android.teamstream:id/score_list_team_score'
  SCORES_GAME_DATE ||= 'id~com.bleacherreport.android.teamstream:id/score_list_game_details_date'
  SCORES_GAME_PERIOD ||= 'id~com.bleacherreport.android.teamstream:id/score_list_game_details_period_and_clock'
  SCORES_TV_STATION ||= 'id~com.bleacherreport.android.teamstream:id/score_list_game_details_station'
  SCORES_TEAM_RECORD ||= 'id~com.bleacherreport.android.teamstream:id/score_list_team_record'
  SCORES_PREVIOUS_DATE ||= 'id~com.bleacherreport.android.teamstream:id/scoresListPagePrevious'
  SCORES_FUTURE_DATE ||= 'id~com.bleacherreport.android.teamstream:id/scoresListNextPage'
  SCORES_CURRENT_DATE ||= 'id~com.bleacherreport.android.teamstream:id/scoresListCurrentPageName'
  SCORE_NO_GAMES ||= 'id~com.bleacherreport.android.teamstream:id/scoresListNoGamesMainText'
  SCORES_STANDING_SEEALL_LINK ||= 'id~com.bleacherreport.android.teamstream:id/score_list_header_standings_see_all'
  ROW_HEADER ||= 'id~com.bleacherreport.android.teamstream:id/settings_header_row'
  CATEGORY_LABEL ||= 'id~com.bleacherreport.android.teamstream:id/category'
  SETTINGS_OPTIONS_NOTE ||= 'id~com.bleacherreport.android.teamstream:id/settings_option_additional_note'
  SETTINGS_OPTION_ROW ||= 'id~com.bleacherreport.android.teamstream:id/settings_option_row'
  TEXT_TITLE ||= 'id~com.bleacherreport.android.teamstream:id/title'
  DETAILS_TXT ||= 'id~com.bleacherreport.android.teamstream:id/details'
  SIGNED_IN_AS_TXT ||= 'id~com.bleacherreport.android.teamstream:id/signed_in_as'
  POPUP_ALERT_TITLE ||= 'id~android:id/alertTitle'
  POPUP_ALERT_MSG ||= 'id~android:id/message'
  POPUP_ALERT_OPTION ||= 'id~android:id/text1'
  FOLLOWER_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_followers'
  FOLLOWING_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_following'
  FB_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_facebook'
  USERNAME_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_username'
  FULL_NAME_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_fullname'
  DOB_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_birthday'
  PHONE_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_phone'
  EMAIL_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_email'
  SCORES_CAROUSEL_LABEL ||= 'id~com.bleacherreport.android.teamstream:id/scores_carousel_section_label'
  SCORES_CAROUSEL ||= 'id~com.bleacherreport.android.teamstream:id/scores_carousel'
  APP_BUILD_VERSION ||= 'id~com.bleacherreport.android.teamstream:id/app_version_build_number'
  COMMENT_COUNT ||= 'id~com.bleacherreport.android.teamstream:id/txt_comment_count'
  COMMENT_SEND_BTN ||= 'id~com.bleacherreport.android.teamstream:id/comment_send_button'
  USERNAME_NAME ||= 'id~com.bleacherreport.android.teamstream:id/username'
  COMMENT_BODY ||= 'id~com.bleacherreport.android.teamstream:id/comment'
  COMMENT_REPLY_BTN ||= 'id~com.bleacherreport.android.teamstream:id/reply'
  HEADLINE_TXTVIEW ||= 'id~com.bleacherreport.android.teamstream:id/headline_textview'
  TOP_NEWS_HEADLINES ||= 'id~com.bleacherreport.android.teamstream:id/top_track_header'
  CONNECT_CONTACT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/asset_imageview'
  CONNECT_FB_BTN ||= 'id~com.bleacherreport.android.teamstream:id/facebook_btn'
  DESCRIPTION_TXTVIEW ||= 'id~com.bleacherreport.android.teamstream:id/description_textview'
  STANDINGS_BTN ||= "xpath~//android.widget.TextView[contains(@text, 'Standings')]"
  SCHEDULES_BTN ||= "xpath~//android.widget.TextView[contains(@text, 'Schedule')]"
  GET_TICKETS_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_tickets'
  SORT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_sort'
  GENERAL_TEXT ||= 'id~com.bleacherreport.android.teamstream:id/text'
  USERNAME_TEXTVIEW ||= 'id~com.bleacherreport.android.teamstream:id/username_textview'
  MY_PROFILE_BTN ||= "xpath~//android.widget.TextView[contains(@text, 'My Profile')]"
  DETAILS_LINK_TXT ||= 'id~com.bleacherreport.android.teamstream:id/details'
  VIDEO_AUTOPLAY_BTN ||= "xpath~//android.widget.TextView[contains(@text, 'Wi-Fi and Mobile Data')]"
  STREAM_EDIT_BTN ||= 'id~com.bleacherreport.android.teamstream:id/menu_add_player'
  FIRST_TEAM_TXT ||= 'id~com.bleacherreport.android.teamstream:id/label'
  PROFILE_MUTED_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_profile_muted'
  TXT_PROMPT_BANNER ||= 'id~com.bleacherreport.android.teamstream:id/txt_prompt'
  USER_BIO_TXT ||= 'id~com.bleacherreport.android.teamstream:id/txt_bio'
  USER_PROFILE_BIO ||= 'id~com.bleacherreport.android.teamstream:id/bio'
  SORT_ORDER_LABEL ||= 'id~com.bleacherreport.android.teamstream:id/sort_order_label'
  CALENDAR_MONTH_NAME ||= 'id~com.bleacherreport.android.teamstream:id/month_name'
  POST_BODY_TXT ||= 'id~com.bleacherreport.android.teamstream:id/bodyText'

  POST_CHAR_LIMIT ||= 'id~com.bleacherreport.android.teamstream:id/characterLimitView'
  GAMECAST_COMMENTS ||= 'id~com.bleacherreport.android.teamstream:id/gamecast_comments_textview'
  TEAM_1_NAME ||= 'id~com.bleacherreport.android.teamstream:id/scoreboardTeam1Name'
  TEAM_2_NAME ||= 'id~com.bleacherreport.android.teamstream:id/scoreboardTeam2Name'
  RECENT_PACK_STATE ||= 'id~com.bleacherreport.android.teamstream:id/stateText'
  SEE_ALL_VIDEOS ||= 'id~com.bleacherreport.android.teamstream:id/openButton'
  FULL_RECAP_AND_HIGHLIGHTS ||= 'id~com.bleacherreport.android.teamstream:id/gamecastTrackFollowButton'
  TEAM_NAME ||= 'id~com.bleacherreport.android.teamstream:id/team_name'
  RECOMMENDATION_HEADING_TXT ||= 'id~com.bleacherreport.android.teamstream:id/recommendations_heading'
  NO_PACKS_TXT ||= 'id~com.bleacherreport.android.teamstream:id/no_packs_text'
  PACK_STATE_TXT ||= 'id~com.bleacherreport.android.teamstream:id/state'
  COMMUNITY_NAME_TXT ||= 'id~com.bleacherreport.android.teamstream:id/community_name'
  ODDS_LABEL_TXT ||= 'id~com.bleacherreport.android.teamstream:id/bettingText'
  GOLF_TEAM_NAME ||= 'id~com.bleacherreport.android.teamstream:id/nameWrapper'

  # SWITCH Elements
  TOGGLE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/selected_check'

  # TWITTER Elements
  TWEET_USERNAME ||= 'id~com.bleacherreport.android.teamstream:id/txt_user_name'
  TWEET_IMG_PROFILE ||= 'id~com.bleacherreport.android.teamstream:id/img_profile'
  TWEET_BIRD_ICON ||= 'id~com.bleacherreport.android.teamstream:id/img_twitter'

  # ARTICLE Elements
  STREAM_NAME ||= 'id~com.bleacherreport.android.teamstream:id/associated_stream_name'
  STREAM_LOGO_IMG ||= 'id~com.bleacherreport.android.teamstream:id/associated_stream_logo'
  STREAM_TIMESTAMP ||= 'id~com.bleacherreport.android.teamstream:id/time_ago'
  ALERT_ARTICLE_MESSAGE ||= 'id~com.bleacherreport.android.teamstream:id/alerts_inbox_message'
  COMMENTARY_TITLE ||= 'id~com.bleacherreport.android.teamstream:id/commentary_title'
  ALERT_DENY_BTN ||= 'id~com.android.packageinstaller:id/permission_deny_button'
  ALERT_ALLOW_BTN ||= 'id~com.android.permissioncontroller:id/permission_allow_button'

  # VIDEO Elements
  VIDEO_MUTE_BTN ||= 'id~com.bleacherreport.android.teamstream:id/inline_video_mute'
  VIDEO_PLAY_BTN ||= 'id~com.bleacherreport.android.teamstream:id/video_play_button'

  # ADVERTISEMENT Elements
  AD_IMAGE ||= 'id~com.bleacherreport.android.teamstream:id/ad_image'

  # FRAME LAYOUT Elements
  BR_VIDEO_MODULE ||= 'id~com.bleacherreport.android.teamstream:id/ad_video_container'
  RECOMMENDATION_CAROUSEL_MODULE ||= 'id~com.bleacherreport.android.teamstream:id/recommendations_carousel'
  BET_TRACK_HOLDER ||= 'id~com.bleacherreport.android.teamstream:id/bet_track_card_holder'

  # CHECKVIEW Elements
  MY_TEAMS_ONLY_BTN ||= "xpath~//android.widget.CheckedTextView[contains(@text, 'My Teams Only')]"
  TOP_NEWS_MY_TEAMS_BTN ||= "xpath~//android.widget.CheckedTextView[contains(@text, 'Top News + My Teams')]"
  WIFI_CELLULAR_BTN ||= "xpath~//android.widget.CheckedTextView[contains(@text, 'Wi-Fi and Mobile Data')]"
  NEVER_AUTOPLAY_BTN ||= "xpath~//android.widget.CheckedTextView[contains(@text, 'Never Autoplay Videos')]"

  # CHECKBOX Elements
  CHECKBOX_BTN ||= 'id~com.bleacherreport.android.teamstream:id/selected_check_box'
end